### ISSUE TITLE
DMU rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [silasary/Penny-Dreadful-Discord-Bot#10504]
- [x] Copy legal_cards.txt to pdmtgo.com (S3). Manually set the metadata Content-Type=text/plain; charset=utf-8.
- [ ] Run post_rotation task for decksite python3 run.py maintenance post_rotation
- [x] Restart decksite touch /etc/uwsgi/vassals/decksite.ini
- [x] Send !suppresshype to PDBot
- [x] Restart or update Discord Bot taking note of [#5490](https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/issues/5490)
- [x] Update [Gatherling](http://www.gatherling.com/util/updateDefaultFormats.php) legal cards list
- [x] Add any new (or newly-legal) DFCs to PDBot
- [x] Remove any no-longer-game-breaking bugged cards from the Gatherling banned list, and add any new ones.
(Katelyn can update Scryfall but if not) ping @Csuhta#3333 on their Discord for Scryfall
- [x] Email richard@mtggoldfish.com for MTG Goldfish
- [ ] ~~Ping yeaGO on his wall at tappedout~~
- [x] Archive all the Run_XXX.txt files so that the next rotation will start running correctly
- [x] Call !rotate on the bot

- [ ] upload legal_cards.txt to S3
- [ ] upload DMU_legal_cards.txt to S3
- [x] ping scryfall
- [x] email mtggoldfish
- [x] restart discordbot
- [x] run post_rotation

Reported on rotation by rotation script
