### ISSUE TITLE
BRO rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [silasary/Penny-Dreadful-Discord-Bot#10714]
https://pennydreadfulmagic.com/admin/rotation/

- [x] upload legal_cards.txt to S3
- [ ] upload BRO_legal_cards.txt to S3
- [x] ping scryfall
- [x] email mtggoldfish
- [x] restart discordbot
- [x] run post_rotation

Reported on rotation by rotation script
