### ISSUE TITLE
ONE rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [silasary/Penny-Dreadful-Discord-Bot#10938]
https://pennydreadfulmagic.com/admin/rotation/

- [x] upload legal_cards.txt to S3
- [x] upload ONE_legal_cards.txt to S3
- [ ] ping scryfall
- [ ] email mtggoldfish
- [x] restart discordbot
- [x] run post_rotation
- [ ] Update Gatherling legal cards list

Reported on rotation by rotation script
