### ISSUE TITLE
MID rotation checklist

### ISSUE THREAD

**Issue by vorpal-buildbot** [silasary/Penny-Dreadful-Discord-Bot#9212]
https://pennydreadfulmagic.com/admin/rotation/

- [x] upload legal_cards.txt to S3
- [x] upload MID_legal_cards.txt to S3
- [x] ping scryfall
- [x] email mtggoldfish
~~[ ] ping tappedout~~

Reported on rotation by rotation script

**Comment by Wizzerinus** [comment]
* [x] Update dreadrise card list

**Comment by bakert** [comment]
I don't think we do tapped out any more. They haven't updated in a long long time.
